/**
 * Property-based testing helper (spec §15.7, backlog B-107).
 *
 * Generates a deterministic property-test skeleton (invariant checks over
 * generated inputs) from a natural-language invariant. This scaffolds the
 * test; it does NOT claim the property holds — the generated test must be
 * compiled and run by the verification gate before any completion claim.
 *
 * `generatePropertySkeleton` is pure and deterministic for unit testing.
 */

export interface Invariant {
  /** Target module import spec, e.g. "../../src/foo.ts". */
  target: string;
  /** Function/symbol under test. */
  fn: string;
  /** Natural-language invariant, e.g. "returns true for all even integers". */
  invariant: string;
  /** Sample generator expression, e.g. "fuzzInt()" or "n". */
  generator: string;
}

/** A deterministic, seeded pseudo-random generator for property inputs. */
export function makeFuzzGen(seed = 0): () => number {
  let state = seed >>> 0 || 1;
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 0xffffffff;
  };
}

/**
 * Generate a property-test skeleton. The returned source is a starting point
 * the verification gate must compile + run; it is NOT trusted evidence.
 */
export function generatePropertySkeleton(inv: Invariant): string {
  const fn = inv.fn;
  const target = inv.target;
  const checks = buildChecks(inv.fn, inv.invariant, inv.generator);
  return `// Property-based skeleton generated by pi-engineering-runtime (B-107).
// This is a scaffold: it MUST be compiled and run by the verification gate
// before any completion claim. The invariant is NOT trusted as-is.
import { ${fn} } from ${JSON.stringify(target)};

function fuzzInt(seed = 0) {
  let s = (seed >>> 0) || 1;
  return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 0xffffffff; };
}

export function checkProperty(seed = 0, rounds = 100): { ok: boolean; failures: Array<{ seed: number; input: number }> } {
  const rnd = fuzzInt(seed);
  const failures = [];
  for (let r = 0; r < rounds; r++) {
    const input = Math.floor(rnd() * 1000);
${checks.map((c) => `    try { if (!(${c})) failures.push({ seed, input }); } catch { failures.push({ seed, input }); }`).join("\n")}
  }
  return { ok: failures.length === 0, failures };
}
`;
}

function buildChecks(fn: string, invariant: string, generator: string): string[] {
  const text = invariant.toLowerCase();
  const checks: string[] = [];
  if (/even/.test(text)) checks.push(`${generator} % 2 === 0 ? ${fn}(${generator}) : true`);
  if (/odd/.test(text)) checks.push(`${generator} % 2 === 1 ? ${fn}(${generator}) : true`);
  if (/positive/.test(text)) checks.push(`${generator} > 0 ? ${fn}(${generator}) : true`);
  if (/non-?negative/.test(text)) checks.push(`${generator} >= 0 ? ${fn}(${generator}) : true`);
  if (/truth/.test(text)) checks.push(`${fn}(${generator}) === true || ${fn}(${generator}) === false`);
  // Fallback: assert the function runs without throwing on the generated inputs.
  if (checks.length === 0)
    checks.push(`typeof ${fn}(${generator}) === "boolean" || typeof ${fn}(${generator}) === "number"`);
  return checks;
}
